FROM ruby:3.2.3
RUN gem update --system
# Install Bundler and Rails
RUN gem install bundler && gem install rails -v 7.2.2
# Set environment variables
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# Install dependencies
RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& NODE_MAJOR=20 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
&& apt-get update -qq && apt-get install -y nodejs yarn vim build-essential libpq-dev libvips-dev \
&& apt-get clean

# Ensure the latest version of Yarn is installed
RUN apt-get remove -y yarn || true \
&& npm install -g yarn --force

# Create app directory
RUN mkdir /myapp
WORKDIR /myapp

# Copy application files
COPY . /myapp

# Install application dependencies
RUN bundle install